---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
...
spec:
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 2.4.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: 466269de453b7b35c71589d229f542cc3e1cb45a
 
